//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TinyCad.rc
//
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             102
#define IDS_RECURSION                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDP_OLE_INIT_FAILED             105
#define IDM_FILEPAGESET                 106
#define IDM_FILEIMPORT                  107
#define IDM_FILEEXPORT                  108
#define IDM_FILEDESIGN                  109
#define IDS_PROPSHT_CAPTION1            110
#define IDD_DETAILS_PAGE1               111
#define IDD_DETAILS_PAGE2               112
#define IDM_VIEWGRID                    115
#define IDM_VIEWSHOWPOS                 116
#define IDR_MAINFRAME                   128
#define IDR_TCADTYPE                    129
#define IDR_LIBTYPE                     130
#define IDR_DRAWING                     131
#define IDR_ANNOTATE                    133
#define IDR_DRAWBUS                     134
#define IDR_DRAWGROUP                   135
#define IDR_POLYGON                     135
#define IDR_EDITTOOL                    136
#define IDR_POLYGON_EDIT                137
#define IDR_DUMMY                       139
#define IDR_LIBVIEW                     140
#define IDR_LINETOOL_EDIT               141
#define IDD_EXPORT_PCB                  142
#define IDR_SHEET_MENU                  142
#define IDR_SYMBOL_SHEET_MENU           143
#define IDD_COLOURS                     144
#define IDR_METHOD_EDIT                 144
#define IDD_AUTOSAVE                    145
#define IDR_TXTTYPE                     145
#define IDI_SELECTED_BOX                147
#define IDR_RT_MANIFEST1                147
#define IDI_UNSELECTED_BOX              148
#define IDR_HIERARCHICAL_EDIT           149
#define IDI_ALIGN_LEFT                  150
#define IDI_ALIGN_CENTRE                151
#define IDI_ALIGN_RIGHT                 152
#define IDI_ALIGN_TOP                   153
#define IDI_ALIGN_MIDDLE                154
#define IDI_ALIGN_BOTTOM                155
#define IDM_EDITREDO                    160
#define IDB_BITMAP1                     160
#define IDM_EDITMOVE                    162
#define IDM_EDITDRAG                    163
#define IDB_BITMAP2                     165
#define IDM_EDITDUP                     166
#define IDM_EDITREPEAT                  167
#define IDB_BITMAP3                     167
#define IDM_EDITROTATE                  168
#define IDM_EDITUNDO                    169
#define IDM_LIBPIN                      170
#define IDM_LIBLIB                      171
#define IDS_NOHIERARCHICAL_SYMBOL       172
#define IDM_SPECIALBOM                  180
#define IDM_SPECIALANNOTATE             181
#define IDM_SPECIALNET                  183
#define IDM_SPECIALCHECK                184
#define IDM_REPEATNAMEUP                194
#define IDM_REPEATNAMEDOWN              195
#define IDM_REPEATPINUP                 196
#define IDM_REPEATPINDOWN               197
#define METHODBOX_MIRROR                202
#define METHODBOX_UP                    203
#define METHODBOX_DOWN                  204
#define METHODBOX_LEFT                  205
#define METHODBOX_RIGHT                 206
#define TEXTBOX_LABEL                   207
#define LIBRARYBOX_ADD                  208
#define LINEBOX_FREE                    209
#define LINEBOX_90                      210
#define LINEBOX_45                      211
#define METHODBOX_NAMEON                212
#define LINEBOX_ARC1                    212
#define METHODBOX_NAME                  213
#define LINEBOX_ARC2                    213
#define METHODBOX_REFON                 215
#define METHODBOX_REF                   216
#define POWERBOX_TEXT                   217
#define LIBRARYBOX_REMOVE               218
#define PAGESIZE_PRINTERSET             219
#define LIBRARYBOX_NEW                  219
#define LIBRARYBOX_EDIT                 220
#define LIBRARYBOX_UPGRADE              225
#define METHODBOX_OTHERON               226
#define METHODBOX_OTHER                 227
#define SYMBOLRENAME_OLD                228
#define SYMBOLRENAME_NEW                229
#define TEXTBOX_LEFT                    230
#define TEXTBOX_UP                      231
#define METHODBOX_PPP                   232
#define LIBRARYBOX_AVAILABLE            234
#define PAGESIZE_A4                     235
#define PAGESIZE_A3                     236
#define PAGESIZE_A2                     237
#define PAGESIZE_A1                     238
#define PAGESIZE_PRINTER                239
#define PAGESIZE_LAND                   240
#define PAGESIZE_PORT                   241
#define IDD_PARTS                       242
#define PAGESIZE_WIDTH                  243
#define PAGESIZE_HEIGHT                 246
#define ANNOTATEBOX_ADD                 253
#define ANNOTATEBOX_REMOVE              254
#define ANNOTATEBOX_ALL                 255
#define ANNOTATEBOX_UNNUM               256
#define ANNOTATEBOX_MATCH               257
#define ANNOTATEBOX_MATCHVAL            258
#define ANNOTATEBOX_DEF                 259
#define ANNOTATEBOX_START               260
#define ANNOTATEBOX_STARTVAL            261
#define ERC_UNCONNECT                   264
#define ERC_POWER                       265
#define ERCLIST_LIST                    266
#define ERC_NOCONNECT                   267
#define ERC_NOUTPUT                     268
#define ERC_DUPREF                      269
#define ERC_OUTPUT                      270
#define ERC_UNCONNECTED                 271
#define ERRORBOX_TEXT                   272
#define ERC_OUTPUTTOPWR                 273
#define ROTATEBOX_UP                    274
#define DESIGNBOX_AUTHOR                277
#define DESIGNBOX_TITLE                 278
#define DESIGNBOX_DOCUMENT              279
#define DESIGNBOX_ORGANISATION          280
#define DESIGNBOX_SHEET                 281
#define DESIGNBOX_REVISION              282
#define DESIGNBOX_DISPLAY               283
#define ROTATEBLOCK_MIRROR              284
#define DESIGNBOX_DATE                  285
#define ROTATEBLOCK_LEFT                292
#define ROTATEBLOCK_RIGHT               293
#define POWERBOX_TOP                    305
#define POWERBOX_BOTTOM                 306
#define POWERBOX_LEFT                   307
#define POWERBOX_RIGHT                  308
#define POWERBOX_BAR                    309
#define POWERBOX_CIRCLE                 310
#define POWERBOX_WAVE                   311
#define POWERBOX_ARROW                  312
#define POWERBOX_EARTH                  313
#define PINBOX_UP                       314
#define PINBOX_DOWN                     315
#define PINBOX_LEFT                     316
#define PINBOX_RIGHT                    317
#define PINBOX_NUMBER                   318
#define PINBOX_NAMEON                   319
#define PINBOX_NUMBERON                 320
#define PINBOX_INPUT                    322
#define PINBOX_OUTPUT                   323
#define PINBOX_BIDIR                    324
#define PINBOX_TRISTATE                 325
#define PINBOX_PASSIVE                  326
#define PINBOX_NAME                     332
#define UPDATE_LIBFILE                  340
#define UPDATE_PPP                      345
#define PINBOX_NORMAL                   380
#define PINBOX_DOT                      381
#define PINBOX_CLOCK                    382
#define PINBOX_DCLOCK                   383
#define PINBOX_POWER                    384
#define PINBOX_HIDDEN                   385
#define TEXTBOX_TEXT                    400
#define ID_FIND_FIND                    510
#define ID_FIND_SETTAG                  512
#define IDD_ANNOTATE                    519
#define ID_OPTION_FONT                  520
#define ID_OPTION_LINE                  522
#define IDD_ERCBOX                      524
#define IDD_ERCLIST                     525
#define IDD_FIND                        526
#define IDM_EDITCOPY                    530
#define IDD_PAGESIZE                    530
#define IDM_EDITPASTE                   531
#define IDM_EDITCUT                     532
#define IDD_GETFIND                     532
#define IDD_GRID                        533
#define IDS_CONFIRM_DELETE              533
#define IDD_LIBRARY                     535
#define IDD_NO_TOOL                     537
#define IDD_METHOD                      539
#define IDD_PIN                         540
#define IDD_POSITION                    541
#define IDD_POWER                       542
#define IDD_ROTATE                      543
#define IDD_SETPPP                      544
#define IDD_SYMBOLRENAME                545
#define IDD_TEXT                        546
#define IDD_UPDATE                      547
#define IDD_DRAW_LINE                   549
#define IDD_POLYGON                     551
#define IDM_EDITROTATELEFT              552
#define IDM_EDITROTATERIGHT             553
#define IDM_EDITFLIP                    554
#define IDM_LIBCOPY                     600
#define IDS_NODEFAULT                   1000
#define LINETHICKBOX_THICKNESS          1000
#define IDS_ABORTLOAD                   1001
#define IDC_SPIN1                       1001
#define IDS_ABORTNOTMINE                1002
#define PINBOX_LENGTH                   1002
#define IDS_ABORTSAVE                   1003
#define POSITIONBOX_POS                 1003
#define IDS_ABORTVERSION                1004
#define IDC_UPDATE_LIST                 1004
#define PRINT_BANDW                     1005
#define IDS_ABORTAUTOSAVE               1005
#define IDS_BADPRINT                    1006
#define IDC_REF_PAINTER                 1006
#define IDS_NOSYMBOL                    1007
#define IDC_SCALE                       1007
#define IDS_BADDETAILS                  1008
#define METHODBOX_RESIZE                1008
#define IDS_NOLIBRARY                   1009
#define IDC_LIST                        1009
#define IDS_LIBTIDIED                   1010
#define IDC_ADD                         1010
#define IDS_BADDEVICE                   1011
#define IDC_DELETE                      1011
#define IDS_COPYPINS                    1012
#define IDC_COLOUR                      1012
#define IDC_ADD_NAME                    1012
#define IDC_DESIGN                      1012
#define IDS_BADPART                     1013
#define IDC_EXAMPLE                     1013
#define IDC_LINE_COLOUR                 1013
#define IDC_DELETE_NAME                 1013
#define IDS_MISSMETH                    1014
#define IDC_TEXT_COLOUR                 1014
#define IDS_MISSREF                     1015
#define IDS_CANNOTOPEN                  1016
#define IDS_DESTIDIED                   1017
#define IDC_INDEX                       1017
#define IDS_TOOMANYFILES                1018
#define IDC_FILL                        1018
#define IDS_IAMICON                     1019
#define IDS_BADLIB                      1020
#define IDC_FILL_COLOUR                 1020
#define IDS_MISSLIB                     1021
#define IDC_VERSION                     1021
#define IDS_NORES                       1022
#define IDC_TEXT_FONT                   1022
#define IDS_NOFIND                      1023
#define IDC_FIT                         1023
#define IDS_DUPNAME                     1024
#define IDC_AUTOSNAP_ENABLE             1024
#define IDC_AUTODRAG_ENABLE             1025
#define IDS_BAD_PPP                     1025
#define IDC_AUTOSNAP_RANGE              1026
#define IDC_AUTOSNAP_UNITS              1027
#define IDC_SHOW_RULERS                 1028
#define IDC_AUTOJUNC_ENABLE             1028
#define IDC_SHOW_SYMBOL                 1029
#define IDC_SEARCH_STRING               1030
#define IDC_RADIO1                      1032
#define IDC_RADIO2                      1033
#define IDC_ORIENTATION                 1038
#define IDC_PIN_TYPE                    1039
#define IDC_ELEC                        1040
#define PINBOX_PIN_POS                  1041
#define IDC_FILE_TYPE                   1043
#define IDC_FILE_NAME                   1044
#define IDC_BROWSE                      1045
#define IDC_COL_WIRE                    1049
#define IDC_COL_JUNCTION                1050
#define IDC_COL_NOCONNECT               1051
#define IDC_COL_PIN                     1052
#define IDC_COL_NOTETEXT_TEXT           1053
#define IDC_COL_POWER                   1054
#define IDC_COL_BUS                     1055
#define IDC_RESET                       1056
#define IDC_COL_BACKGROUND              1057
#define IDC_COL_NOTETEXT_FILL           1058
#define IDC_LIST_NAMES                  1059
#define IDC_COL_NOTETEXT_LINE           1059
#define IDC_AUTOSAVE_ENABLE             1061
#define IDC_AUTOSAVE_BUDDY              1063
#define IDC_SPIN                        1064
#define ID_RENAME_STRING                1065
#define IDC_HORIZ_GUIDE                 1066
#define IDC_VERT_GUIDE                  1067
#define IDC_SHEET1                      1067
#define IDC_SHEET2                      1068
#define IDC_TAB1                        1069
#define IDC_SPICE_MODEL                 1071
#define IDC_SPICE_PROLOG                1072
#define IDC_STATIC1                     1073
#define IDC_STATIC2                     1074
#define IDC_STATIC3                     1075
#define IDC_PREFIX                      1076
#define IDC_STATIC4                     1077
#define IDC_ALL_ATTRS                   1077
#define IDC_ALL_SHEETS                  1078
#define IDC_SPICE_EPILOG                1079
#define IDC_ALL_HIERARCHICAL            1079
#define IDC_PRO_PRIORITY                1080
#define IDC_EPI_PRIORITY                1081
#define IDC_PRO_SPIN                    1082
#define IDC_EPI_SPIN                    1083
#define IDC_STYLE1                      1086
#define IDC_STYLE2                      1087
#define IDC_STYLE3                      1088
#define IDC_STYLE4                      1089
#define ERR_BASE                        1099
#define ERR_UNCONNECT                   1100
#define ERR_POWER                       1101
#define ERR_NOCONNECT                   1102
#define ERR_NOUTPUT                     1103
#define ERR_DUPREF                      1104
#define ERR_OUTPUT                      1105
#define ERR_OUTPUTTOPWR                 1106
#define ERR_UNCONNECTED                 1107
#define ERR_OUTPUTBIDIR                 1108
#define ERR_POWERBIDIR                  1109
#define ERR_NOERROR                     1110
#define IDS_ABORTINDEXSAVE              1111
#define ERR_UNRECOP                     1112
#define ERR_UNRECOBJ                    1113
#define IDS_NO_SYM_DELETE               1114
#define IDS_DELETE_SHEET                1115
#define IDS_MUSTUPGRADE                 1116
#define ERR_UNASSIGNEDREFDES            1117
#define ERR_NONDISTINCTNET              1118
#define ERR_MULTIPLENETNAMES            1119
#define ID_FIND_TAG                     1205
#define FINDBOX_STRING                  1214
#define UPDATE_DESCRIPTION              1230
#define FINDGET_LIST                    1231
#define GRIDBOX_SHOW                    1232
#define GRIDBOX_NORMAL                  1233
#define GRIDBOX_FINE                    1234
#define GRIDBOX_USER                    1235
#define GRIDBOX_MM                      1237
#define GRIDBOX_INCHES                  1238
#define GRIDBOX_SPACING                 1239
#define GRIDBOX_SNAP                    1240
#define GRIDBOX_SCROLLBAR               1241
#define GRIDBOX_UNITS                   1259
#define LINETHICKBOX_STYLE              1269
#define ID_OPTIONS_TOOLBARS_SYMBOL      1284
#define IDD_PRINT                       1538
#define IDD_FILLSTYLE                   1539
#define IDD_AUTOSNAP                    1540
#define IDD_EXPORT_PNG                  1541
#define IDD_RENAME_SHEET                1542
#define IDD_REPLACE                     1543
#define IDD_LABEL                       1544
#define IDD_EXPORT_BOM                  1545
#define IDC_LABEL_DIR1                  1546
#define IDD_HIERARCHICAL                1546
#define IDC_LABEL_DIR2                  1547
#define IDD_DRAW_POLY                   1547
#define IDC_LABEL_DIR3                  1548
#define IDD_LINE                        1548
#define IDC_LABEL_DIR4                  1549
#define IDD_TOOLNOTETEXT                1549
#define IDC_ENTIRE_NET                  1551
#define IDC_DEFAULT_STYLE               1552
#define IDC_CHECK1                      1553
#define IDC_ROTATE                      1554
#define METHODBOX_SHOWPOWER             1555
#define IDC_CENTRE_NAME                 1556
#define ERC_MULTIPLENETNAMES            1564
#define ERC_NONCASEDISTINCT             1565
#define ERC_UNASSIGNEDREFDES            1566
#define IDC_SYMBOL_TREE                 1567
#define IDC_UNITSTRING                  1571
#define IDC_NOTETEXT_RECTANGLE          1573
#define IDC_NOTETEXT_ROUNDEDRECT        1574
#define IDC_NOTETEXT_NOBORDER           1575
#define IDC_NOTETEXT_TABWIDTH           1580
#define IDC_BUTTON_ANNOTATE             1581
#define IDC_BUTTON_PCB_NETLIST          1582
#define IDC_BUTTON_SPICE_NETLIST        1583
#define IDC_WINDOWS_VERSION             1584
#define IDR_POSITION                    1585
#define LIBRARYBOX_CLEANUP              1600
#define IDC_ZOOMCURSOR                  30988
#define IDC_REFCURSOR                   30989
#define AFX_IDC_TRACK_MOVE              30990
#define AFX_IDC_TRACK_BLOCK             30991
#define IDM_TOOLLABEL                   32771
#define IDM_TOOLWIRE                    32772
#define IDM_TOOLJUNC                    32773
#define IDM_TOOLPOWER                   32774
#define IDM_TOOLBUSNAME                 32775
#define IDM_BUSSLASH                    32776
#define IDM_TOOLBUS                     32777
#define IDM_TOOLTEXT                    32778
#define IDM_TOOLLINE                    32779
#define IDM_TOOLCIRCLE                  32780
#define IDM_TOOLSQUARE                  32781
#define IDM_EDITDELITEM                 32782
#define IDM_EDITEDIT                    32783
#define IDM_BUSBACK                     32784
#define IDM_TOOLCONNECT                 32785
#define IDM_TOOLGET                     32786
#define IDM_TOOLARC                     32787
#define IDM_VIEWCENTRE                  32788
#define IDM_VIEWZOOMIN                  32789
#define IDM_VIEWZOOMOUT                 32790
#define ID_SYMBOL_DELETESYMBOL          32791
#define ID_SYMBOL_RENAMESYMBOL          32792
#define IDS_NOUPGRADE                   32793
#define IDS_NOJUNCTION                  32794
#define IDS_NOUPGRADENEED               32795
#define ID_SYMBOL_EDITSYMBOL            32796
#define ID_SYMBOL_NEWSYMBOL             32797
#define ID_LIBRARY_ADDPIN               32798
#define ID_LIBRARY_SELECTPARTINPACKAGE  32799
#define IDS_NODELETE                    32800
#define IDM_SNAPTOGRID                  32809
#define ID_VIEW_FILETOOLBAR             32810
#define ID_VIEW_EDITTOOLBAR             32811
#define ID_VIEW_GROUPTOOLBAR            32812
#define ID_VIEW_ANNOTATIONTOOLBAR       32813
#define ID_VIEW_BUSTOOLBAR              32814
#define ID_HELP_GOTOTINYCADWEBSITE      32815
#define ID_LIBRARY_REFRESHSYMBOLSFROMLIBRARIES 32816
#define ID_HELP_HELP                    32817
#define ID_RULER_HORIZ                  32818
#define ID_RULER_VERT                   32819
#define IDM_TOOLPOLYGON                 32821
#define IDM_VIEW_OPTIONS                32824
#define ID_CONTEXT_FINISHPOLYGON        32826
#define ID_CONTEXT_CANCELDRAWING        32827
#define ID_CONTEXT_ARCIN                32828
#define ID_CONTEXT_ARCOUT               32829
#define ID_CONTEXT_FREELINE             32830
#define ID_CONTEXT_FINISHDRAWING        32831
#define ID_CONTEXT_ADDHANDLE            32836
#define ID_CONTEXT_DELETEHANDLE         32837
#define ID_CONTEXT_ZORDER_BRINGTOFRONT  32839
#define ID_CONTEXT_ZORDER_SENDTOBACK    32840
#define ID_RESIZE                       32841
#define IDM_EDITDUPLICATE               32843
#define ID_SPECIAL_CREATESPICEFILE      32845
#define ID_EDIT_COPYTO                  32846
#define ID_CONTEXT_MAKEVERTICAL         32847
#define ID_CONTEXT_MAKEHORIZONTAL       32848
#define ID_FILE_SAVEASBITMAP            32850
#define ID_CONTEXT_SENDTO               32852
#define ID_OPTIONS_COLOURS              32853
#define ID_CONTEXT_DUPLICATESYMBOL      32854
#define ID_SYMBOL_SYMBOLPROPERTIES      32855
#define ID_FILE_EXPORTLIBRARY           32856
#define ID_FILE_IMPORTLIBRARY           32857
#define ID_CONTEXT_EXPORTSYMBOL         32858
#define ID_CONTEXT_ADDSHEET             32859
#define ID_CONTEXT_DELETESHEET          32860
#define ID_CONTEXT_RENAMESHEET          32861
#define ID_LIBRARY_SETPARTSPERPACKAGE   32862
#define ID_CONTEXT_REPLACESYMBOL        32863
#define ID_HORZ_RESIZE                  32864
#define ID_EDIT_INSERTPICTURE           32865
#define ID_HELP_EMAILFORSUPPORT         32866
#define ID_CONTEXT_ADDHIERARCHICALSYMBOL 32867
#define IDM_TOOL_HIERARCHICAL           32868
#define IDM_TOOLHIERARCHICAL            32869
#define ID_CONTEXT_OPENDESIGN           32872
#define ID_CONTEXT_RELOADSYMBOLFROMDESIGN 32873
#define ID_LIBRARY_HOMOGENEOUS          32876
#define ID_LIBRARY_HETEROGENEOUS        32877
#define ID_OPTIONS_TOGGLE_UNITS         32884
#define IDM_TOGGLE_GRIDSIZE             32888
#define ID_HELP_OPENTINYCADUSERMANUAL   32894
#define IDM_EDITSELECTALL               32895
#define IDM_TOOLORIGIN                  32896
#define IDM_TOOLNOTETEXT                32897
#define ID_SPECIAL_VHDL                 32899
#define IDM_SPECIALVHDLCHECK            32901
#define ID_CONTEXT_CURVE                32902
#define IDC_SCALING                     40000
#define IDS_NOCLEANUP                   40001
#define POSITIONBOX_GRIDSIZE            40002
#define POSITIONBOX_GRIDUNITS           40003
#define ID_CONTEXT_COPY_TO              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32903
#define _APS_NEXT_CONTROL_VALUE         1586
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
